language: php

sudo: false

services:
  - mongodb

matrix:
  fast_finish: true
  include:
      # 3.4.*
    - php: 5.6
      env: SYMFONY_VERSION=3.4.*
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
      # 4.3.*
    - php: 7.1
      env: SYMFONY_VERSION=4.3.*
    - php: 7.2
      env: SYMFONY_VERSION=4.3.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "extension = mongodb.so" >> /home/travis/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer require alcaeus/mongo-php-adapter --ignore-platform-reqs --prefer-dist --no-interaction $COMPOSER_FLAGS
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ./bin/phpspec run -fpretty --verbose
