language: php


php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script: ./bin/phpspec run -fpretty --verbose

notifications:
    on_success: never
    on_failure: always
