<?php

namespace Gesdinet\JWTRefreshTokenBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\Repository\DocumentRepository as ForwardDocumentRepository;
use Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken;

// @todo: remove this condition and extend directly from `ForwardDocumentRepository`
// when support for "doctrine/mongodb-odm <2.0" is removed.
if (class_exists(ForwardDocumentRepository::class, false)) {
    class BaseRepository extends ForwardDocumentRepository
    {
    }
} else {
    class BaseRepository extends DocumentRepository
    {
    }
}

/**
 * RefreshTokenRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefreshTokenRepository extends BaseRepository
{
    /**
     * @param null $datetime
     *
     * @return RefreshToken[]
     */
    public function findInvalid($datetime = null)
    {
        $datetime = (null === $datetime) ? new \DateTime() : $datetime;

        $queryBuilder = $this->createQueryBuilder()
            ->field('valid')->lt($datetime);

        return $queryBuilder->getQuery()->execute();
    }
}
