# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Psalm Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '17 14 * * 4'

permissions:
  contents: read

jobs:
  php-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    strategy:
      fail-fast: false
      matrix:
        php: ['8.4']
        extensions: ['curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: ${{ matrix.extensions }}

      - name: Update Composer dependencies
        run: composer update

      - name: Install PHP MongoDB extension
        run: |
          sudo apt-get update
          sudo apt-get install -y php-mongodb

      - name: Install Composer dependencies
        run: composer install

      - name: Psalm Security Scan
        uses: docker://ghcr.io/psalm/psalm-security-scan:5.25.0
        with:
          composer_require_dev: false
          composer_ignore_platform_reqs: false
          security_analysis: true
          show_info: true
          php_version: ${{ matrix.php }}

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
