name: 'Run Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: 'ubuntu-22.04'
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
        symfony: ['6.4.*', '7.2.*', '7.3.*']
        composer-flags: ['--prefer-stable']
        can-fail: [false]
        extensions: ['curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip']
        include:
          - php: '8.2'
            symfony: '6.4.*'
            composer-flags: '--prefer-stable --prefer-lowest'
            can-fail: false
            extensions: 'curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip'

    name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, flex
          extensions: ${{ matrix.extensions }}
          coverage: none

      - name: Setup MongoDB
        id: setup-mongodb
        uses: mongodb-labs/drivers-evergreen-tools@master
        with:
          version: '6.0'
          topology: server

      - name: Install dependencies
        run: composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Run PHPUnit
        run: bin/phpunit
        env:
          DOCTRINE_MONGODB_SERVER: ${{ steps.setup-mongodb.outputs.cluster-uri }}
