name: 'Run Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0]
        symfony: [3.4.*, 4.4.*, 5.2.*, 5.3.*]
        composer-flags: ['--prefer-stable']
        can-fail: [false]
        include:
          - php: 7.4
            symfony: 3.4.*
            composer-flags: '--prefer-stable --prefer-lowest'
            can-fail: false
          - php: 8.0
            symfony: 5.4.*@dev
            composer-flags: ''
            can-fail: true
        exclude:
          - php: 8.0
            symfony: 3.4.*

    name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer global require --no-scripts --no-plugins symfony/flex
          composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Run phpspec
        run: bin/phpspec run -fpretty --verbose

      - name: Run PHPUnit
        run: bin/phpunit --verbose
