name: 'Run Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0]
        symfony: [3.4.*, 4.4.*, 5.2.*, 5.3.*]
        composer-flags: ['--prefer-stable']
        can-fail: [false]
        extensions: ['curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip']
        include:
          - php: 7.4
            symfony: 3.4.*
            composer-flags: '--prefer-stable --prefer-lowest'
            can-fail: false
            extensions: 'curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip'
          - php: 8.0
            symfony: 5.4.*@dev
            composer-flags: ''
            can-fail: true
            extensions: 'curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip'
          - php: 8.1
            symfony: 5.3.*
            composer-flags: '--ignore-platform-req=php'
            can-fail: true
            extensions: 'curl, iconv, mbstring, mongodb-1.11.0alpha1, pdo, pdo_sqlite, sqlite, zip'
        exclude:
          - php: 8.0
            symfony: 3.4.*

    name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, flex
          extensions: ${{ matrix.extensions }}
          coverage: none

      - name: Setup MongoDB
        id: setup-mongodb
        uses: mongodb-labs/drivers-evergreen-tools@master
        with:
          version: 4.4
          topology: server

      - name: Install dependencies
        run: composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Run phpspec
        run: bin/phpspec run -fpretty --verbose

      - name: Run PHPUnit
        run: bin/phpunit --verbose
        env:
          DOCTRINE_MONGODB_SERVER: ${{ steps.setup-mongodb.outputs.cluster-uri }}
